#1. numbers = (10, 20, 30, 40, 50)Add 60 to the end,Replace 30 with 35.
numbers = (10, 20, 30, 40, 50)
print(type(numbers))
numbers=list(numbers)
print(type(numbers))
numbers.append(60)
print(numbers)
numbers[2]=35
print(numbers)
numbers=tuple(numbers)
print(type(numbers))
#2. values = (15, 5, 30, 25, 10) arrange the elements in ascending order.
values = (15, 5, 30, 25, 10)
print(type(values))
values=list(values)
print(type(values))
values.sort()
print(values)
numbers=tuple(numbers)
print(type(numbers))
#3. fruits = ("apple", "banana", "cherry", "banana", "mango", "banana")
#Count occurrences of "banana",Remove all occurrences of "banana".
fruits = ("apple", "banana", "cherry", "banana", "mango", "banana")
print(type(fruits))
fruits=list(fruits)
print(type(fruits))
y=fruits.count("banana")
print(y)
fruits.remove("banana")
print(fruits)
fruits.remove("banana")
print(fruits)
fruits.remove("banana")
print(fruits)
#4. names = ("Alice", "Bob", "Charlie", "David") Reverse the order of elements using sort method.
names = ("Alice", "Bob", "Charlie", "David")
print(type(names))
names=list(names)
print(type(names))
names.reverse()
print(names)
#5. colors = ("red", "blue", "green")add "yellow" at index 1,Extend with ["purple", "orange"]
colors = ("red", "blue", "green")
print(type(colors))
colors=list(colors)
print(type(colors))
colors.insert(1,"yellow")
print(colors)
x=["purple", "orange"]
colors.extend(x)
print(colors)